### ISSUE TITLE
Load test for larger writes

### ISSUE THREAD

**Issue by simonw** [simonw/django_sqlite_benchmark#3]
> And for a write load test... how about ingesting the Twitter firehose? Or the GitHub firehose, which is easier to access.

_Originally posted by @simonw in https://github.com/simonw/django_sqlite_benchmark/issues/2#issuecomment-1286188778_

**Comment by simonw** [comment]
Here's the API for GitHub public events: https://docs.github.com/en/rest/activity/events#list-public-events
```
curl \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  https://api.github.com/events
```
Also:
> Events are optimized for polling with the "ETag" header. If no new events have been triggered, you will see a "304 Not Modified" response, and your current rate limit will be untouched. There is also an "X-Poll-Interval" header that specifies how often (in seconds) you are allowed to poll.

Not clear to me yet if the public `/events` endpoint will return results fast enough that it's a good test here (without it getting rate limited).

**Comment by simonw** [comment]
I hit that API with `httpx` and a new fine-grained personal access token created at https://github.com/settings/tokens?type=beta

Here are the headers I got back:

```
{'server': 'GitHub.com',
 'date': 'Thu, 20 Oct 2022 22:05:17 GMT',
 'content-type': 'application/json; charset=utf-8',
 'transfer-encoding': 'chunked',
 'cache-control': 'private, max-age=60, s-maxage=60',
 'vary': 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
 'etag': 'W/"ad056bff7f57788963c5c30f70803fe335643e7b25832727545f631f25ea74fd"',
 'last-modified': 'Thu, 20 Oct 2022 22:00:17 GMT',
 'x-poll-interval': '60',
 'github-authentication-token-expiration': '2023-01-18 15:03:53 -0800',
 'x-github-media-type': 'github.v3; format=json',
 'link': '<https://api.github.com/events?page=2>; rel="next", <https://api.github.com/events?page=10>; rel="last"',
 'x-ratelimit-limit': '5000',
 'x-ratelimit-remaining': '2100',
 'x-ratelimit-reset': '1666304214',
 'x-ratelimit-used': '2900',
 'x-ratelimit-resource': 'core',
 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
 'access-control-allow-origin': '*',
 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
 'x-frame-options': 'deny',
 'x-content-type-options': 'nosniff',
 'x-xss-protection': '0',
 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
 'content-security-policy': "default-src 'none'",
 'content-encoding': 'gzip',
 'x-github-request-id': 'F372:0A68:3949687:3A5F282:6351C61C'}
```

**Comment by simonw** [comment]
'x-poll-interval': '60'

That suggests I should only hit it once every 60 seconds, so this is not a good enough firehose for this load test.

**Comment by simonw** [comment]
I'm not going to use a firehose API at all: I'm going to generate random test data as fast as I can instead.

**Comment by simonw** [comment]
I'll use data created using https://datasette.io/tools/sqlite-generate

**Comment by simonw** [comment]
Ran this:

    sqlite-generate generated.db -t 1 -c 10 --fks 0 -r 10000

Gave me a table with 10,000 rows.

**Comment by simonw** [comment]
I fiddled around a bit and did this:
```
sqlite-utils drop-table generated.db last_with_must
sqlite-utils drop-table generated.db summer_establish_least
sqlite-utils generated.db 'alter table whole_so_against rename to rows'
sqlite-utils vacuum generated.db
```
Now I have a database with a single table with this schema:
```sql
CREATE TABLE "rows" (
   [id] INTEGER PRIMARY KEY,
   [name] TEXT,
   [campaign] TEXT,
   [voice] TEXT,
   [recognize] TEXT,
   [inside] FLOAT,
   [growth] TEXT,
   [side] FLOAT,
   [yard] TEXT,
   [discussion] TEXT
);
```
It's 4.2MB: https://static.simonwillison.net/static/2022/generated.db

**Comment by simonw** [comment]
OK, with this benchmark I am getting a small number of errors. Here's it running with WAL mode on (but the default timeout, which seems to be 5s as opposed to 20s):
```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                         2803    20(0.71%) |    272      15    5812     57 |  149.98        1.07
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                      2803    20(0.71%) |    272      15    5812     57 |  149.98        1.07
```
That was running under Uvicorn:

    python -m uvicorn django_sqlite_benchmark.asgi:application

With this benchmark line (which just runs the new write test, as I had commented out the previous counter test):

    locust --headless --users 100 --spawn-rate 5 -H http://127.0.0.1:8000

**Comment by simonw** [comment]
I bumped the timeout back up to 20s and now I don't get any errors again:
```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                         4134     0(0.00%) |    370      14   17604     66 |  145.38        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                      4134     0(0.00%) |    370      14   17604     66 |  145.38        0.00
```

**Comment by simonw** [comment]
The error tracebacks (back without the timeout) look like this:

```
Internal Server Error: /write/
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/django_sqlite_benchmark-VtO7axdH/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/simon/.local/share/virtualenvs/django_sqlite_benchmark-VtO7axdH/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

**Comment by simonw** [comment]
... which makes sense when you look at the response percentiles:
```
Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                                69     95    120    160    350    970   2400   3700   5600   5600   5600   1976
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                             69     95    120    160    350    970   2400   3700   5600   5600   5600   1976
```
A small fraction of them take longer than 5000ms - which is the default value for `timeout` if you don't set one according to https://docs.python.org/3/library/sqlite3.html#sqlite3.connect

**Comment by simonw** [comment]
Since it's only about 4MB I decided to check `generated.db` (the database full of random data I use for the write benchmark) into the repo.

This means you can now explore it in Datasette Lite here: https://lite.datasette.io/?url=https://github.com/simonw/django_sqlite_benchmark/blob/4d968426f7cf65582b482fd08d5993e3dfe12cd4/generated.db

**Comment by simonw** [comment]
I tried this test using Gunicorn with four workers:
```
python -m gunicorn django_sqlite_benchmark.asgi:application \
  -k uvicorn.workers.UvicornWorker -w 4
```
```
locust --headless --users 100 --spawn-rate 5 -H http://127.0.0.1:8000
```
```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                        11702     0(0.00%) |    164       9    9587     47 |  388.09        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     11702     0(0.00%) |    164       9    9587     47 |  388.09        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                                47     68     95    130    300    770   1500   2100   4800   6500   9600  11702
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                             47     68     95    130    300    770   1500   2100   4800   6500   9600  11702
```
It hit almost 400 of those write requests per second, with 0 errors - and as you can see 90% of requests were served in <300ms (with 9.6s as the absolute slowest request time under full load). Pretty impressive!

**Comment by simonw** [comment]
Each write is a POST of a JSON object that looks like this one:
```json
{
    "id": 2,
    "name": "Aaron Gonzales",
    "campaign": "Write not necessary course garden gas. Guy mean woman yes image down.\nAsk admit open energy trip community Mrs. Law money follow find third level. Especially upon cover PM Mr thus price.",
    "voice": "Jasmine Gardner",
    "recognize": "Jacob Harrington",
    "inside": 68.275367974752,
    "growth": "joseph91@example.org",
    "side": 589918.13785629,
    "yard": "Employee center speak little go raise firm. Admit likely store often though. Respond per side thus painting push.",
    "discussion": "70233"
}
```
That's just over 500 bytes when serialized.

**Comment by simonw** [comment]
Out of curiosity I decided to run Gunicorn with 8 workers (up from 4) like this:

    python -m gunicorn django_sqlite_benchmark.asgi:application \
      -k uvicorn.workers.UvicornWorker -w 8

And ran Locust with a spawn rate of 20 rather than 5, which means that within 5 seconds it should hit the full 100 concurrent users:

    locust --headless --users 100 --spawn-rate 20 -H http://127.0.0.1:8000

This gave me 500 requests/second with no errors, but I did get this warning from Locust:

`[2022-10-21 20:04:01,827] Simons-MacBook-Pro-2.local/WARNING/locust.runners: CPU usage was too high at some point during the test! See https://docs.locust.io/en/stable/running-distributed.html for how to distribute the load over multiple CPU cores or machines`

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                        12648     0(0.00%) |    168      14    7182    110 |  499.08        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     12648     0(0.00%) |    168      14    7182    110 |  499.08        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                               110    130    150    180    290    510   1000   1400   2800   3600   7200  12648
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            110    130    150    180    290    510   1000   1400   2800   3600   7200  12648
```
So at this point I need to move off my laptop (a 2019 Intel MacBook Pro) and start running tests with a separate machine for Locust.

Laptop specs used for these tests so far (with a whole bunch of other software running, so hardly a clean environment):

<img width="242" alt="CleanShot 2022-10-21 at 20 06 21@2x" src="https://user-images.githubusercontent.com/9599/197316380-f6f011f4-fe2a-4a13-bf7c-792638bac1b2.png">

**Comment by simonw** [comment]
Also worth noting that all of these benchmarks have been run using ASGI mode, e.g. like this:

```
python -m gunicorn django_sqlite_benchmark.asgi:application \
  -k uvicorn.workers.UvicornWorker -w 8
```
Would be interesting to compare this to Django running in WSGI mode, which presumably avoids the overhead of constantly switching from ASGI to threaded and back again.

**Comment by simonw** [comment]
https://docs.djangoproject.com/en/4.1/howto/deployment/wsgi/gunicorn/ indicates this should work:

    python -m gunicorn django_sqlite_benchmark.wsgi

I tried that (which defaults to 1 worker) and ran this:

    locust --headless --users 100 --spawn-rate 20 -H http://127.0.0.1:8000

And got this - just 37.45 requests/second, less than I expected:

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                          475     0(0.00%) |   1943      42    3200   2100 |   37.45        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                       475     0(0.00%) |   1943      42    3200   2100 |   37.45        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                              2100   2600   2800   2900   3000   3100   3100   3200   3200   3200   3200    475
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                           2100   2600   2800   2900   3000   3100   3100   3200   3200   3200   3200    475
```
Also VERY poor percentile performance - 50% took less than 2.1s and got worse from there. Weird.

With 4 workers:

    python -m gunicorn django_sqlite_benchmark.wsgi -w 4

I got this:

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                         3736     0(0.00%) |    388      20     986    400 |  220.57        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                      3736     0(0.00%) |    388      20     986    400 |  220.57        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                               400    460    500    530    610    680    750    790    870    990    990   3736
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            400    460    500    530    610    680    750    790    870    990    990   3736
```
That's better - 220 requests/second and 400ms 50% (990ms 100%) - but still less requests/second than ASGI mode.

**Comment by simonw** [comment]
More curiosity: since I have `Postgres.app` on this laptop already I decided to try running against PostgreSQL too for comparison.
```
/Applications/Postgres.app/Contents/Versions/12/bin/psql -p5432 "postgres"
postgres=# CREATE DATABASE django_sqlite_benchmark;
```
The in `settings.py`:

```python
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "django_sqlite_benchmark",
    }
}
```
I ran:

    pip install psycopg2-binary

Then:

    ./manage.py migrate

That gave me a working PostgreSQL setup. I started Gunicorn WSGI:

    python -m gunicorn django_sqlite_benchmark.wsgi -w 4

And ran the test:

    locust --headless --users 100 --spawn-rate 20 -H http://127.0.0.1:8000

Result:

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                         8165     0(0.00%) |    240      38     351    260 |  374.39        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                      8165     0(0.00%) |    240      38     351    260 |  374.39        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                               260    260    270    270    270    280    290    310    350    350    350   8165
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            260    260    270    270    270    280    290    310    350    350    350   8165
```
That's 374.39 requests/second against PostgreSQL.

Same again, this time in ASGI mode:
```
python -m gunicorn django_sqlite_benchmark.asgi:application \
  -k uvicorn.workers.UvicornWorker -w 4
```

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                         8358     0(0.00%) |    223      23     535    230 |  360.07        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                      8358     0(0.00%) |    223      23     535    230 |  360.07        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                               230    260    290    300    330    360    390    420    490    540    540   8358
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            230    260    290    300    330    360    390    420    490    540    540   8358
```
That's 360 requests/second, very slightly less than WSGI mode.

So with PostgreSQL WSGI slightly beats ASGI, but with SQLite ASGI 2x beats WSGI! Surprised by that.

**Comment by simonw** [comment]
Tried 8 WSGI workers against PostgreSQL and got the "too much CPU being used" warning again, and about 466 requests/second:

    python -m gunicorn django_sqlite_benchmark.wsgi -w 8

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /write/                                                                        10940     0(0.00%) |    189      31     545    200 |  466.53        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     10940     0(0.00%) |    189      31     545    200 |  466.53        0.00

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
POST     /write/                                                                               200    220    220    230    240    260    290    320    380    540    550  10940
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                            200    220    220    230    240    260    290    320    380    540    550  10940
```

**Comment by simonw** [comment]
I should benchmark a `/hello/` endpoint that doesn't interact with a database at all too.

**Comment by michaellenaghan** [comment]
One thing to highlight, even though it's kind of obvious: generally speaking Postgres would be remote and involve network latency.
